baseURL = "https://ICtuvk123.github.io/"
languageCode = "en-us"
title = "Timothy's Blog"
theme = "PaperMod"

[params]
    env = "production"
    title = "Timothy's Blog"
    description = "AI, Math, and CS Notes"
    author = "Timothy"

    ShowToc = true          # è‡ªåŠ¨ç”Ÿæˆæ–‡ç« ç›®å½•
    TocOpen = false         
    math = true             # å¼€å¯ LaTeX æ•°å­¦å…¬å¼æ”¯æŒ

    # é¦–é¡µä¿¡æ¯
    [params.homeInfoParams]
        Title = "Hi there ğŸ‘‹"
        Content = "Welcome to my technical blog. I focus on AI and CS. This is where I share my notes and insights."

# GitHub é“¾æ¥
    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/ICtuvk123"

    # Gmail é“¾æ¥
    [[params.socialIcons]]
        name = "email"
        url = "mailto:zhutianci0820@gmail.com"

    # æ­¦å¤§é‚®ç®±
    [[params.socialIcons]]
        name = "email"
        url = "mailto:zhutianci@whu.edu.cn"

    # QQ é“¾æ¥
    [[params.socialIcons]]
    	name = "qq"
    	url = "tencent://message/?uin=1283177969"

